# requires root permissions
sudo: required
# install docker inside container
services:
  - docker
# to be done before running any test or before deployment
# putting together the initial image
before_install:
  - docker build -t manishjuriani/docker-react -f Dockerfile.dev .

# to run tests for the initial image
script:
  - docker run -e CI=true manishjuriani/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-247504479588"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
